const pageCodeMap: Record<string, string[]> = {
    "/": [
        '"use client";',
        "",
        "import React, { useEffect, useRef, useState } from \"react\";",
        "import { TextScramble } from \"@/utils/TextScramble\";",
        "import WireframeWave from \"@/components/shared/WireframeWave\";",
        "import ProjectModal from \"@/components/layout/ProjectModal\";",
        "",
        "const Hero: React.FC = () => {",
        "    const titleRef = useRef<HTMLHeadingElement>(null);",
        "    const fxRef = useRef<TextScramble | null>(null);",
        "    const [isModalOpen, setIsModalOpen] = useState(false);",
        "",
        "    useEffect(() => {",
        "        if (titleRef.current) {",
        "            const fx = new TextScramble(titleRef.current);",
        "            fx.setText(\"Профессиональное программирование цифровых продуктов\");",
        "            fxRef.current = fx;",
        "        }",
        "    }, []);",
        "",
        "    const handleHover = () => {",
        "        if (fxRef.current) {",
        "            fxRef.current.setText(\"Профессиональное программирование цифровых продуктов\");",
        "        }",
        "    };",
        "",
        "    return (",
        "        <>",
        "            <div className=\"fixed top-0 left-0 w-full h-screen z-0\" style={{ backgroundColor: \"#D7001D\" }}>",
        "                <WireframeWave",
        "                    color={0xFB0037}",
        "                    opacity={1.0}",
        "                    speed={0.002}",
        "                    lineCount={45}",
        "                    lineSpacing={35}",
        "                    angle={20}",
        "                />",
        "",
        "                <div className=\"relative z-10 max-w-7xl mx-auto h-full px-6 flex flex-col justify-center items-start pt-20 gap-8 text-white\">",
        "                    <h1",
        "                        ref={titleRef}",
        "                        onMouseEnter={handleHover}",
        "                        className=\"cursor-pointer text-[90px] leading-[90px] tracking-[-0.04em] font-medium",
        "                                   sm:text-[60px] sm:leading-[65px]",
        "                                   xs:text-[40px] xs:leading-[45px]\"",
        "                        style={{ fontFamily: \"'Manrope', sans-serif\" }}",
        "                    >",
        "                        Профессиональное программирование цифровых продуктов",
        "                    </h1>",
        "",
        "                    <p className=\"text-[32px] font-mono sm:text-[24px] xs:text-[20px]\">",
        "                        Web, mobile, design, ml, analytics, big.data",
        "                    </p>",
        "",
        "                    <a",
        "                        onClick={() => setIsModalOpen(true)}",
        "                        className=\"cursor-pointer px-10 py-6 border border-white rounded-full text-[32px] font-semibold hover:bg-white hover:text-red-600 transition sm:text-[24px] xs:text-[20px]\"",
        "                    >",
        "                        Реализовать проект",
        "                    </a>",
        "                </div>",
        "            </div>",
        "",
        "            <ProjectModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} />",
        "        </>",
        "    );",
        "};",
        "",
        "export default Hero;",
    ],
    "/mobile": [
        '"use client";',
        "",
        'import React from "react";',
        "",
        "const Hero: React.FC = () => {",
        "    return (",
        '        <section',
        '            className="bg-white min-h-screen flex items-center px-6 pt-20 sm:pt-32 lg:pt-40 sm:px-10 lg:px-20"',
        '            style={{fontFamily: "\'Manrope\', sans-serif"}}',
        "        >",
        '            <div className="max-w-7xl mx-auto flex flex-col lg:flex-row items-center justify-between gap-10">',
        "",
        "                {/* Левая часть */}",
        '                <div className="flex-1 max-w-[540px]">',
        '                    <div className="w-10 h-[6px] bg-[#D7001D] rounded-full mb-6"></div>',
        "",
        '                    <h1 className="text-4xl sm:text-5xl font-medium leading-tight mb-4 text-black">',
        "                        Мобильная Разработка",
        "                    </h1>",
        "",
        '                    <p className="text-gray-800 text-[18px] leading-relaxed mb-8">',
        "                        Мобильная разработка под ключ для бизнеса в Казахстане и СНГ.",
        "                        Чистая архитектура, продуманный UX/UI и стабильная работа на",
        "                        iOS и Android. От идеи до готового приложения — системный и",
        "                        надёжный подход.",
        "                    </p>",
        "",
        '                    <a',
        '                        href="#contact-form"',
        '                        className="relative inline-block px-6 py-3 font-semibold border-2 border-[#D7001D] text-[#D7001D] rounded-md overflow-hidden transition-colors duration-300 group"',
        "                    >",
        '                        <span className="relative z-10 group-hover:text-white transition-colors duration-300">',
        "                            Реализовать продукт →",
        "                        </span>",
        '                        <span',
        '                            className="',
        "                                absolute z-0 bottom-0 right-0 w-0 h-0",
        "                                bg-[#D7001D] rounded-full",
        "                                transition-all duration-700 ease-in-out",
        "                                group-hover:w-[400%] group-hover:h-[400%]",
        "                                group-hover:bottom-[-100%] group-hover:right-[-100%]",
        '                            "',
        "                        ></span>",
        "                    </a>",
        "                </div>",
        "",
        "                {/* Правая часть — телефоны */}",
        '                <div className="flex-1 flex justify-center items-end gap-6">',
        '                    <img src="/images/phones/phone-1.png" alt="Phone 1" className="w-[160px] sm:w-[180px] md:w-[200px]" />',
        '                    <img src="/images/phones/phone-2.png" alt="Phone 2" className="w-[160px] sm:w-[180px] md:w-[200px]" />',
        '                    <img src="/images/phones/phone-3.png" alt="Phone 3" className="w-[160px] sm:w-[180px] md:w-[200px]" />',
        "                </div>",
        "            </div>",
        "        </section>",
        "    );",
        "};",
        "",
        "export default Hero;",
    ],
    "/uxui": [
        '"use client";',
        "",
        'import React from "react";',
        'import Image from "next/image";',
        "",
        "const UiUxHero: React.FC = () => {",
        "  return (",
        '    <section',
        '      className="bg-[#D7001D] text-white py-24 px-6 sm:px-10 lg:px-20 rounded-b-[40px]"',
        '      style={{ fontFamily: "\'Manrope\', sans-serif" }}',
        "    >",
        '      <div className="max-w-7xl mx-auto flex flex-col lg:flex-row items-center justify-between gap-12">',
        "",
        "        {/* Левая часть */}",
        '        <div className="flex-1">',
        '          <div className="w-10 h-[6px] bg-white rounded-full mb-6" />',
        '          <h1 className="text-5xl font-normal mb-6">UX/UI design</h1>',
        '          <p className="text-lg sm:text-xl mb-8 max-w-xl font-light leading-relaxed">',
        "            Разрабатываем UX/UI-дизайн для сайтов, мобильных приложений и веб-сервисов.",
        "            Фокус на удобство, визуальную чистоту и цели бизнеса. Адаптируем под пользователей",
        "            из Казахстана и СНГ.",
        "          </p>",
        '          <a',
        '            href="#contact-form"',
        '            className="relative inline-flex items-center gap-2 font-semibold text-[#D7001D] border-2 border-white rounded-md overflow-hidden transition-colors duration-300 group px-6 py-3"',
        "          >",
        '            <span className="relative z-10 group-hover:text-white transition-colors duration-300">',
        "              Реализовать →",
        "            </span>",
        '            <span',
        '              className="absolutе z-0 bottom-0 right-0 w-0 h-0 bg-white rounded-full',
        '                         transition-all duration-700 ease-in-out',
        '                         group-hover:w-[400%] group-hover:h-[400%]',
        '                         group-hover:bottom-[-100%] group-hover:right-[-100%]"',
        "            />",
        "          </a>",
        "        </div>",
        "",
        "        {/* Правая часть */}",
        '        <div className="flex-1 flex justify-center">',
        '          <Image',
        '            src="/images/uiux/mockups.png"',
        '            alt="UIUX design preview"',
        "            width={700}",
        "            height={600}",
        '            className="rounded-3xl shadow-xl"',
        "            priority",
        "          />",
        "        </div>",
        "",
        "      </div>",
        "    </section>",
        "  );",
        "};",
        "",
        "export default UiUxHero;",
    ],
    "/ml": [
        '"use client";',
        "",
        'import React from "react";',
        "",
        'const MLHero: React.FC = () => {',
        "  return (",
        "    <section",
        '      className="bg-white py-20 px-6 sm:px-10 lg:px-20 min-h-screen flex items-center"',
        '      style={{ fontFamily: "var(--font-manrope)" }}',
        "    >",
        '      <div className="max-w-7xl mx-auto w-full flex flex-col lg:flex-row items-center justify-between gap-12">',
        "",
        "        {/* Left column */}",
        '        <div className="flex-1">',
        '          <div className="w-10 h-1.5 bg-[#D7001D] rounded-full mb-6" />',
        '          <h1 className="text-5xl lg:text-6xl font-normal mb-6 text-black leading-tight">',
        "            ML разработка",
        "          </h1>",
        '          <p className="text-lg sm:text-xl mb-8 text-gray-800 max-w-lg leading-relaxed">',
        "            ML-разработка и искусственный интеллект под ключ — для бизнеса в Казахстане и СНГ.",
        "            Создаём решения на основе машинного обучения и нейросетей: от предиктивной аналитики",
        "            до интеллектуальной автоматизации процессов.",
        "          </p>",
        '          <a',
        '            href="#contact-form"',
        '            className="inline-flex items-center bg-[#D7001D] text-white font-semibold px-6 py-3 rounded-md transition hover:bg-opacity-90"',
        "          >",
        '            Реализовать продукт&nbsp;<span className="text-xl">→</span>',
        "          </a>",
        "        </div>",
        "",
        "        {/* Right column */}",
        '        <div className="flex-1 flex justify-center">',
        '          <div',
        '            className="w-full max-w-md bg-gray-100 rounded-3xl shadow-xl"',
        '            style={{ aspectRatio: "4/3" }}',
        "          />",
        "        </div>",
        "",
        "      </div>",
        "    </section>",
        "  );",
        "};",
        "",
        "export default MLHero;",
    ],

    "/web": [
        '"use client";',
        "",
        'import React from "react";',
        'import Image from "next/image";',
        "",
        'const WebHero: React.FC = () => {',
        "  return (",
        '    <section',
        '      className="bg-white min-h-screen pt-12 sm:pt-32 lg:pt-0 flex items-center"',
        '      style={{ fontFamily: "\'Manrope\', sans-serif" }}',
        "    >",
        "",
        "      {/* Mobile Layout */}",
        '      <div className="lg:hidden flex flex-col items-center px-6 sm:px-10 gap-8">',
        '        <div className="w-full">',
        '          <Image',
        '            src="/images/web/desktop.png"',
        '            alt="Web development preview"',
        "            width={800}",
        "            height={500}",
        '            className=""',
        "            priority",
        "          />",
        "        </div>",
        '        <div className="text-left px-4">',
        '          <h1 className="text-3xl font-semibold text-black mb-4">Веб - разработка</h1>',
        '          <p className="text-gray-800 text-base leading-relaxed mb-6">',
        "            Предлагаем веб-разработку под ключ для бизнеса в Казахстане и странах СНГ. Создаём сайты и веб-сервисы, которые быстро работают, масштабируются и решают реальные задачи.",
        "          </p>",
        '          <a',
        '            href="#contact-form"',
        '            className="inline-block px-6 py-3 font-semibold bg-[#D7001D] text-white rounded-md hover:bg-[#bb0017] transition"',
        "          >",
        "            Реализовать продукт →",
        "          </a>",
        "        </div>",
        "      </div>",
        "",
        "      {/* Desktop Layout */}",
        '      <div className="hidden lg:flex max-w-7xl mx-auto h-full w-full items-center justify-between gap-12">',
        '        <div className="max-w-[540px]">',
        '          <div className="w-10 h-[6px] bg-[#D7001D] rounded-full mb-6" />',
        '          <h1 className="text-5xl font-medium leading-tight mb-4 text-black">',
        "            Веб-разработка",
        "          </h1>",
        '          <p className="text-gray-800 text-[18px] leading-relaxed mb-8">',
        "            Предлагаем веб-разработку под ключ для бизнеса в Казахстане и странах СНГ. Создаём сайты и веб-сервисы, которые быстро работают, масштабируются и решают реальные задачи.",
        "          </p>",
        '          <a',
        '            href="#contact-form"',
        '            className="relative inline-block px-6 py-3 font-semibold border-2 border-[#D7001D] text-[#D7001D] rounded-md overflow-hidden transition-colors duration-300 group"',
        "          >",
        '            <span className="relative z-10 group-hover:text-white transition-colors duration-300">',
        "              Реализовать продукт →",
        "            </span>",
        '            <span',
        '              className="absolute z-0 bottom-0 right-0 w-0 h-0 bg-[#D7001D] rounded-full transition-all duration-700 ease-in-out group-hover:w-[400%] group-hover:h-[400%] group-hover:bottom-[-100%] group-hover:right-[-100%]"',
        "            />",
        "          </a>",
        "        </div>",
        '        <div className="flex-1 flex justify-center">',
        '          <Image',
        '            src="/images/web/desktop.png"',
        '            alt="Web development preview"',
        "            width={800}",
        "            height={500}",
        '            className=""',
        "            priority",
        "          />",
        "        </div>",
        "      </div>",
        "",
        "    </section>",
        "  );",
        "};",
        "",
        "export default WebHero;",
    ],

};

export default pageCodeMap;